# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'TimeManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TimeManager
  pod 'SkyFloatingLabelTextField', '~> 3.6'
  pod 'MagicalRecord', '~> 2.3'

  target 'TimeManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TimeManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
